apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ngrok.fullname" . }}-pods
  labels:
    {{- include "ngrok.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ngrok.fullname" . }}-pods
subjects:
- kind: ServiceAccount
  name: {{ include "ngrok.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "ngrok" }}
