apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ngrok.fullname" . }}-configmap
  labels:
    {{- include "ngrok.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ngrok.fullname" . }}-configmap
subjects:
- kind: ServiceAccount
  name: {{ include "ngrok.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "ngrok" }}
