apiVersion: v1
kind: Service
metadata:
  name: {{ include "ngrok.fullname" . }}
  labels:
    {{- include "ngrok.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports}}
    - port: {{ $value }}
      targetPort: {{ $value }}
      protocol: TCP
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "ngrok.selectorLabels" . | nindent 4 }}
