tls:
  existingSecret: "ngrok-secret"

db:
  type: "sqlite" # allowed : postgres, mysql (both not tested yet)
  host: "localhost"
  port: 5432
  user: postgres
  password: supersecretpassw0rd

persistence:
  resourcePolicy: "keep"
  persistentVolumeClaim:
    db:
      existingClaim: ""
      # Specify the "storageClass" used to provision the volume. Or the default
      # StorageClass will be used (the default).
      # Set it to "-" to disable dynamic provisioning
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations: {}
    registry:
      existingClaim: ""
      # Specify the "storageClass" used to provision the volume. Or the default
      # StorageClass will be used (the default).
      # Set it to "-" to disable dynamic provisioning
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations: {}

env:
  LOG_LEVEL: "DEBUG"
  TLS_CERT_PATH: "/tls/tls.crt"
  TLS_KEY_PATH: "/tls/tls.key"
  HTTP_LISTEN_ADDR: ":80"
  HTTPS_LISTEN_ADDR: ":443"
  TUNNEL_LISTEN_ADDR: ":4443"
  ADMIN_ADDR: ":4111"
  HTTP_ADDR: ":4112"
  DOMAIN: "ngrok.me"
  PROXY_MAX_POOL_SIZE: 10
  CONNECTION_TIMEOUT_SECONDS: 10

# Default values for ngrok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ngrok
  pullPolicy: IfNotPresent
  tag: "1"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
    webadmin: 4111
    client : 4443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
